### PR TITLE
1.19.2

### PR DESCRIPTION
**Pull request by mrsterner**

### CODE REVIEW

**Comment by Titaniumtown** [comment]
Please merge! Been waiting for this mod to get updated!

**Comment by EGOIST1372** [comment]
@mrsterner can you make a 1.19.3 port as well?
thanks in advance <3

**Comment by EGOIST1372** [comment]
@mrsterner can you build artifact since it seems that it failed

**Comment by mrsterner** [comment]
It failed because i didnt have time to finish it all, still one sting left to port

**Review by Titaniumtown — APPROVED** [review]
1.19.2 works perfectly for me

**Comment by EGOIST1372** [comment]
@mrsterner any update on 1.19.3?
thanks in advance <3

**Review by RedXStone — APPROVED** [review]

**Comment by Dragon-Seeker** [comment]
1.19 version will be out within the coming days, thank you for the PR.

**Pull request closed without merging**
